source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.2'
use_frameworks!

target 'S3TransferManagerSampleSwift' do
    pod 'AWSS3', '~> 2.4.12'
    pod 'ELCImagePickerController'
    pod 'JTSImageViewController'
end
